[advisories]
version = 2
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
confidence-threshold = 0.9
# copyleft = "deny"

allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "MPL-2.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
