[package]
name = "alloy-rlp-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
alloy-rlp = { path = "../crates/rlp" }
libfuzzer-sys = "0.4"

[[bin]]
name = "rlp_list"
path = "fuzz_targets/rlp_list.rs"
test = false
doc = false
bench = false

[workspace]
